### ISSUE TITLE
Zip adapter with v2

### ISSUE THREAD

**Issue by tylerwiegand** [thephpleague/flysystem-ziparchive#16]
on the 2.x branch, I can't seem to configure this zip adapter.

```yaml
flysystem:
  storages:
    default.storage:
      adapter: 'local'
      options:
        directory: '%kernel.cache_dir%'
    default.zip:
      adapter: 'zip'
      options:
        directory: '%kernel.cache_dir%'
```

When attempting to use `$defaultZip` in the same manner as the automatically autowired `$defaultStorage` I get this:
```
In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
                                                                                                   
  The service "App\Command\WhateverCommand" has a dependency on a non-existent service "zip".  
                                                                                                   
```

So I think ok, maybe that doesn't exist, I'll register it like a custom adapter. So I change my adapter to reference the class (with or without quotes):

```yaml
      adapter: League\Flysystem\ZipArchive\ZipArchiveAdapter
```

Result: 
```
  The service "App\Command\WhateverCommand" has a dependency on a non-existent service "League\Flysystem\ZipArchive\ZipArchiveAdapter".  
```
Ok, no big deal. I'll just register it as a service with an alias.

flysystem.yaml
```yaml
      adapter: 'zip_archive_adapter'
```

services.yaml:
```yaml
services:
  zip_archive_adapter:
    '@League\Flysystem\ZipArchive\ZipArchiveAdapter'
```
Result:
```
In DefinitionErrorExceptionPass.php line 54:
                                                                                                                                                                                                               
  Cannot autowire service "zip_archive_adapter": argument "$zipArchiveProvider" of method "League\Flysystem\ZipArchive\ZipArchiveAdapter::__construct()" references interface "League\Flysystem\ZipArchive\Zi  
  pArchiveProvider" but no such service exists. Did you create a class that implements this interface?                                                                                                         
                                                                                                                                                           
```

Ok ok, I just need to pass arguments...oh but that means the Provider needs...everything...hmmm also this adapter looks drastically different than the other 2.x providers in the [new docs](https://flysystem.thephpleague.com/v2/docs/)... so I feel like I'm spinning my wheels here. Is the v2 just not ready for the cool new automatic autowiring? 

I'm attempting to configure all the paths in the config so I don't need to use the "old" v1 instantiation for a Filesystem/Adapter, especially for tests, especially now that the MountManager is deprecated... any ideas?

Symfony 4.4
